/*****************************************************************************
*****         (C)2011-2014 FLIR Commercial Systems, Inc.                 *****
*****                       All Rights Reserved.                         *****
*****                                                                    *****
*****     Source data and code may NOT be distributed without the        *****
*****     prior written consent from FLIR Commercial Systems, Inc.       *****
*****                                                                    *****
*****     FLIR PROVIDES THIS CODE ON AN "AS IS" BASIS FOR USE BY         *****
*****     RECIPIENT AT ITS OWN RISK.  FLIR DISCLAIMS ALL WARRANTIES,     *****
*****     WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING WITHOUT       *****
*****     LIMITATION ANY IMPLIED WARRANTIES OF TITLE,                    *****
*****     NON-INFRINGEMENT OF THIRD PARTY RIGHTS, MERCHANTABILITY,       *****
*****     OR FITNESS FOR A PARTICULAR PURPOSE.                           *****
*****                                                                    *****
*****     FLIR Commercial Systems, Inc. reserves the right to make       *****
*****     changes without further notice to any content herein to        *****
*****     improve reliability, function or design. FLIR Commercial       *****
*****     Systems, Inc. shall not assume any liability arising from      *****
*****     the application or use of this code, data or function.         *****
*****                                                                    *****
*****     FLIR Commercial Systems, Inc.                                  *****
*****     Motion Control Systems                                         *****
*****     www.flir.com/mcs                                               *****
*****     mcs-support@flir.com                                           *****
*****************************************************************************/

/* THIS CODE IS GENERATED. DO NOT MODIFY. */

/**
 * \file optable.c
 * \brief Opcode table and lookup utilities.
 *
 * \var cpi_optable
 * \brief Opcode lookup table.
 *
 * The SDK ships with this table containing every allowable opcode. As long as
 * the table is not trimmed, lookup is O(1) via direct indexing off the integer
 * value of cpi_opcode. If the table is trimmed, then CPI_CONFIG_USE_OP_LKUP
 * must be defined. This definition builds a binary search lookup function as
 * an alternative lookup method.
 */

#include <stdlib.h>
#include <string.h>
#include "opcodes.h"

#define NEMB(array)     (sizeof(array) / sizeof(array[0]))

/* trimming this table is only allowed if CPI_CONFIG_USE_OP_LKUP is defined */
struct cpi_opent cpi_optable[] = {
    { OP_INVALID,                           "",         ""          },
    { OP_NOOP,                              "",         ""          },
    { OP_PAN_DESIRED_POS_GET,               "i",        ""          },
    { OP_PAN_DESIRED_POS_SET,               "",         "i"         },
    { OP_PAN_DESIRED_POS_REL_SET,           "",         "i"         },
    { OP_PAN_CURRENT_POS_GET,               "i",        ""          },
    { OP_PAN_DESIRED_SPEED_GET,             "i",        ""          },
    { OP_PAN_DESIRED_SPEED_SET,             "",         "i"         },
    { OP_PAN_CURRENT_SPEED_GET,             "i",        ""          },
    { OP_PAN_REL_SPEED_SET,                 "",         "i"         },
    { OP_PAN_UPPER_SPEED_LIMIT_GET,         "i",        ""          },
    { OP_PAN_UPPER_SPEED_LIMIT_SET,         "",         "i"         },
    { OP_PAN_LOWER_SPEED_LIMIT_GET,         "i",        ""          },
    { OP_PAN_LOWER_SPEED_LIMIT_SET,         "",         "i"         },
    { OP_PAN_ACCEL_GET,                     "i",        ""          },
    { OP_PAN_ACCEL_SET,                     "",         "i"         },
    { OP_PAN_BASE_SPEED_GET,                "i",        ""          },
    { OP_PAN_BASE_SPEED_SET,                "",         "i"         },
    { OP_PAN_HOLD_POWER_GET,                "e",        ""          },
    { OP_PAN_HOLD_POWER_SET,                "",         "e"         },
    { OP_PAN_MOVE_POWER_GET,                "e",        ""          },
    { OP_PAN_MOVE_POWER_SET,                "",         "e"         },
    { OP_PAN_MIN_POSITION,                  "i",        ""          },
    { OP_PAN_MAX_POSITION,                  "i",        ""          },
    { OP_PAN_USER_MIN_POS_GET,              "i",        ""          },
    { OP_PAN_USER_MIN_POS_SET,              "",         "i"         },
    { OP_PAN_USER_MAX_POS_GET,              "i",        ""          },
    { OP_PAN_USER_MAX_POS_SET,              "",         "i"         },
    { OP_PAN_RESOLUTION,                    "d",        ""          },
    { OP_PAN_CONTINUOUS_GET,                "e",        ""          },
    { OP_PAN_CONTINUOUS_SET,                "",         "e"         },
    { OP_TILT_DESIRED_POS_GET,              "i",        ""          },
    { OP_TILT_DESIRED_POS_SET,              "",         "i"         },
    { OP_TILT_DESIRED_POS_REL_SET,          "",         "i"         },
    { OP_TILT_CURRENT_POS_GET,              "i",        ""          },
    { OP_TILT_DESIRED_SPEED_GET,            "i",        ""          },
    { OP_TILT_DESIRED_SPEED_SET,            "",         "i"         },
    { OP_TILT_CURRENT_SPEED_GET,            "i",        ""          },
    { OP_TILT_REL_SPEED_SET,                "",         "i"         },
    { OP_TILT_UPPER_SPEED_LIMIT_GET,        "i",        ""          },
    { OP_TILT_UPPER_SPEED_LIMIT_SET,        "",         "i"         },
    { OP_TILT_LOWER_SPEED_LIMIT_GET,        "i",        ""          },
    { OP_TILT_LOWER_SPEED_LIMIT_SET,        "",         "i"         },
    { OP_TILT_ACCEL_GET,                    "i",        ""          },
    { OP_TILT_ACCEL_SET,                    "",         "i"         },
    { OP_TILT_BASE_SPEED_GET,               "i",        ""          },
    { OP_TILT_BASE_SPEED_SET,               "",         "i"         },
    { OP_TILT_HOLD_POWER_GET,               "e",        ""          },
    { OP_TILT_HOLD_POWER_SET,               "",         "e"         },
    { OP_TILT_MOVE_POWER_GET,               "e",        ""          },
    { OP_TILT_MOVE_POWER_SET,               "",         "e"         },
    { OP_TILT_MIN_POSITION,                 "i",        ""          },
    { OP_TILT_MAX_POSITION,                 "i",        ""          },
    { OP_TILT_USER_MIN_POS_GET,             "i",        ""          },
    { OP_TILT_USER_MIN_POS_SET,             "",         "i"         },
    { OP_TILT_USER_MAX_POS_GET,             "i",        ""          },
    { OP_TILT_USER_MAX_POS_SET,             "",         "i"         },
    { OP_TILT_RESOLUTION,                   "d",        ""          },
    { OP_TILT_CONTINUOUS_GET,               "e",        ""          },
    { OP_TILT_CONTINUOUS_SET,               "",         "e"         },
    { OP_GEO_POINT_LAST,                    "ddd",      ""          },
    { OP_GEO_POINT_LANDMARK,                "",         "i"         },
    { OP_GEO_POINT_LLA,                     "",         "ddd"       },
    { OP_GEO_CAL,                           "",         ""          },
    { OP_RESERVED_AAA,                      "",         ""          },
    { OP_RESERVED_AAB,                      "",         ""          },
    { OP_GEO_DIST_LANDMARK,                 "d",        "i"         },
    { OP_GEO_DIST_LLA,                      "d",        "ddd"       },
    { OP_GEO_LLA_GET,                       "ddd",      ""          },
    { OP_GEO_LLA_SET,                       "",         "ddd"       },
    { OP_GEO_PTU_RPY_GET,                   "ddd",      ""          },
    { OP_GEO_PTU_RPY_SET,                   "",         "ddd"       },
    { OP_GEO_ALT_GET,                       "d",        ""          },
    { OP_GEO_ALT_SET,                       "",         "d"         },
    { OP_GEO_LAT_GET,                       "d",        ""          },
    { OP_GEO_LAT_SET,                       "",         "d"         },
    { OP_GEO_LON_GET,                       "d",        ""          },
    { OP_GEO_LON_SET,                       "",         "d"         },
    { OP_GEO_PTU_PITCH_GET,                 "d",        ""          },
    { OP_GEO_PTU_PITCH_SET,                 "",         "d"         },
    { OP_GEO_PTU_ROLL_GET,                  "d",        ""          },
    { OP_GEO_PTU_ROLL_SET,                  "",         "d"         },
    { OP_GEO_PTU_YAW_GET,                   "d",        ""          },
    { OP_GEO_PTU_YAW_SET,                   "",         "d"         },
    { OP_GEO_CAM_PITCH_GET,                 "d",        ""          },
    { OP_GEO_CAM_PITCH_SET,                 "",         "d"         },
    { OP_GEO_CAL_QUALITY_GET,               "d",        ""          },
    { OP_GEO_LAND_PRINT_GET,                "s",        ""          },
    { OP_GEO_LAND_IDX_GET,                  "isdddiid", "i"         },
    { OP_GEO_LAND_NUM_GET,                  "i",        ""          },
    { OP_RESERVED_AAC,                      "",         ""          },
    { OP_GEO_LAND_CLEAR,                    "",         ""          },
    { OP_GEO_LAND_DEL_IDX,                  "",         "i"         },
    { OP_GEO_LAND_DEL_LAST,                 "",         ""          },
    { OP_GEO_LAND_ADD,                      "",         "sddd"      },
    { OP_GEO_DEFAULT_FACTORY,               "",         ""          },
    { OP_GEO_DEFAULT_RESTORE,               "",         ""          },
    { OP_GEO_DEFAULT_SAVE,                  "",         ""          },
    { OP_GEO_STATUS_GET,                    "e",        ""          },
    { OP_GEO_POINT_TYPE_GET,                "e",        ""          },
    { OP_GEO_POINT_TYPE_SET,                "",         "e"         },
    { OP_ISM_STAB_HEAD_RESUME,              "",         ""          },
    { OP_ISM_CMD_MODE_GET,                  "e",        ""          },
    { OP_ISM_CMD_MODE_SET,                  "",         "e"         },
    { OP_ISM_HEAD_PAN_SPD_DES_GET,          "i",        ""          },
    { OP_ISM_HEAD_PAN_SPD_DES_SET,          "",         "i"         },
    { OP_ISM_HEAD_TILT_SPD_DES_GET,         "i",        ""          },
    { OP_ISM_HEAD_TILT_SPD_DES_SET,         "",         "i"         },
    { OP_ISM_HEAD_PAN_SPD_CUR_GET,          "i",        ""          },
    { OP_ISM_HEAD_PAN_SPD_REL_SET,          "",         "i"         },
    { OP_ISM_HEAD_TILT_SPD_CUR_GET,         "i",        ""          },
    { OP_ISM_HEAD_TILT_SPD_REL_SET,         "",         "i"         },
    { OP_ISM_HEAD_PAN_POS_DES_GET,          "i",        ""          },
    { OP_ISM_HEAD_PAN_POS_DES_SET,          "",         "i"         },
    { OP_ISM_HEAD_TILT_POS_DES_GET,         "i",        ""          },
    { OP_ISM_HEAD_TILT_POS_DES_SET,         "",         "i"         },
    { OP_ISM_HEAD_PAN_POS_CUR_GET,          "i",        ""          },
    { OP_ISM_HEAD_PAN_POS_REL_SET,          "",         "i"         },
    { OP_ISM_HEAD_TILT_POS_CUR_GET,         "i",        ""          },
    { OP_ISM_HEAD_TILT_POS_REL_SET,         "",         "i"         },
    { OP_ISM_HEAD_PAN_GAIN_GET,             "d",        ""          },
    { OP_ISM_HEAD_PAN_GAIN_SET,             "",         "d"         },
    { OP_ISM_HEAD_TILT_GAIN_GET,            "d",        ""          },
    { OP_ISM_HEAD_TILT_GAIN_SET,            "",         "d"         },
    { OP_ISM_STAB_PAN_SPD_DES_GET,          "i",        ""          },
    { OP_ISM_STAB_PAN_SPD_DES_SET,          "",         "i"         },
    { OP_ISM_STAB_TILT_SPD_DES_GET,         "i",        ""          },
    { OP_ISM_STAB_TILT_SPD_DES_SET,         "",         "i"         },
    { OP_ISM_STAB_PAN_SPD_CUR_GET,          "i",        ""          },
    { OP_ISM_STAB_PAN_SPD_REL_SET,          "",         "i"         },
    { OP_ISM_STAB_TILT_SPD_CUR_GET,         "i",        ""          },
    { OP_ISM_STAB_TILT_SPD_REL_SET,         "",         "i"         },
    { OP_ISM_STAB_PAN_POS_DES_GET,          "i",        ""          },
    { OP_ISM_STAB_PAN_POS_DES_SET,          "",         "i"         },
    { OP_ISM_STAB_TILT_POS_DES_GET,         "i",        ""          },
    { OP_ISM_STAB_TILT_POS_DES_SET,         "",         "i"         },
    { OP_ISM_STAB_PAN_POS_CUR_GET,          "i",        ""          },
    { OP_ISM_STAB_PAN_POS_REL_SET,          "",         "i"         },
    { OP_ISM_STAB_TILT_POS_CUR_GET,         "i",        ""          },
    { OP_ISM_STAB_TILT_POS_REL_SET,         "",         "i"         },
    { OP_ISM_PAN_KP_GET,                    "d",        ""          },
    { OP_ISM_PAN_KP_SET,                    "",         "d"         },
    { OP_ISM_TILT_KP_GET,                   "d",        ""          },
    { OP_ISM_TILT_KP_SET,                   "",         "d"         },
    { OP_ISM_PAN_KF_GET,                    "d",        ""          },
    { OP_ISM_PAN_KF_SET,                    "",         "d"         },
    { OP_ISM_TILT_KF_GET,                   "d",        ""          },
    { OP_ISM_TILT_KF_SET,                   "",         "d"         },
    { OP_ISM_PAN_KI_GET,                    "d",        ""          },
    { OP_ISM_PAN_KI_SET,                    "",         "d"         },
    { OP_ISM_TILT_KI_GET,                   "d",        ""          },
    { OP_ISM_TILT_KI_SET,                   "",         "d"         },
    { OP_ISM_PAN_KD_GET,                    "d",        ""          },
    { OP_ISM_PAN_KD_SET,                    "",         "d"         },
    { OP_ISM_TILT_KD_GET,                   "d",        ""          },
    { OP_ISM_TILT_KD_SET,                   "",         "d"         },
    { OP_ISM_PAN_KS_GET,                    "d",        ""          },
    { OP_ISM_PAN_KS_SET,                    "",         "d"         },
    { OP_ISM_TILT_KS_GET,                   "d",        ""          },
    { OP_ISM_TILT_KS_SET,                   "",         "d"         },
    { OP_ISM_PAN_KV_GET,                    "d",        ""          },
    { OP_ISM_PAN_KV_SET,                    "",         "d"         },
    { OP_ISM_TILT_KV_GET,                   "d",        ""          },
    { OP_ISM_TILT_KV_SET,                   "",         "d"         },
    { OP_ISM_PAN_KA_GET,                    "d",        ""          },
    { OP_ISM_PAN_KA_SET,                    "",         "d"         },
    { OP_ISM_TILT_KA_GET,                   "d",        ""          },
    { OP_ISM_TILT_KA_SET,                   "",         "d"         },
    { OP_ISM_PAN_VD_GET,                    "d",        ""          },
    { OP_ISM_PAN_VD_SET,                    "",         "d"         },
    { OP_ISM_TILT_VD_GET,                   "d",        ""          },
    { OP_ISM_TILT_VD_SET,                   "",         "d"         },
    { OP_ISM_PAN_PD_GET,                    "d",        ""          },
    { OP_ISM_PAN_PD_SET,                    "",         "d"         },
    { OP_ISM_TILT_PD_GET,                   "d",        ""          },
    { OP_ISM_TILT_PD_SET,                   "",         "d"         },
    { OP_ISM_PAN_IW_GET,                    "d",        ""          },
    { OP_ISM_PAN_IW_SET,                    "",         "d"         },
    { OP_ISM_TILT_IW_GET,                   "d",        ""          },
    { OP_ISM_TILT_IW_SET,                   "",         "d"         },
    { OP_ISM_X_BIAS_GET,                    "d",        ""          },
    { OP_ISM_X_BIAS_SET,                    "",         "d"         },
    { OP_ISM_Y_BIAS_GET,                    "d",        ""          },
    { OP_ISM_Y_BIAS_SET,                    "",         "d"         },
    { OP_ISM_Z_BIAS_GET,                    "d",        ""          },
    { OP_ISM_Z_BIAS_SET,                    "",         "d"         },
    { OP_ISM_DEFAULT_SAVE,                  "",         ""          },
    { OP_ISM_DEFAULT_FACTORY,               "",         ""          },
    { OP_ISM_DEFAULT_RESTORE,               "",         ""          },
    { OP_ISM_STAB_EN,                       "",         "ue"        },
    { OP_ISM_STAB_DIS,                      "",         ""          },
    { OP_ISM_GYRO_CAL,                      "",         ""          },
    { OP_ISM_GYRO_UTC_GET,                  "u",        ""          },
    { OP_ISM_GYRO_UTC_SET,                  "",         "u"         },
    { OP_ISM_LOS_MODE_GET,                  "e",        ""          },
    { OP_ISM_LOS_MODE_SET,                  "",         "e"         },
    { OP_ISM_GYRO_UPGRADE,                  "",         ""          },
    { OP_ISM_GYRO_FIRMWARE_STATUS_GET,      "e",        ""          },
    { OP_RESERVED_AAD,                      "",         ""          },
    { OP_RESERVED_AAE,                      "",         ""          },
    { OP_ISM_STATUS_GET,                    "e",        ""          },
    { OP_RESERVED_AAF,                      "",         ""          },
    { OP_RESERVED_AAG,                      "",         ""          },
    { OP_ISM_RESET_UP_NORTH,                "",         ""          },
    { OP_ISM_CAM_PITCH_OFFSET_GET,          "d",        ""          },
    { OP_ISM_CAM_PITCH_OFFSET_SET,          "",         "d"         },
    { OP_CONTROL_TYPE_GET,                  "e",        ""          },
    { OP_CONTROL_TYPE_SET,                  "",         "e"         },
    { OP_CONTROL_PAN_CORRECTIONS_GET,       "u",        ""          },
    { OP_CONTROL_TILT_CORRECTIONS_GET,      "u",        ""          },
    { OP_TIMESTAMP_COUNT_GET,               "u",        ""          },
    { OP_TIMESTAMP_FREQUENCY,               "u",        ""          },
    { OP_EXEC_MODE_GET,                     "e",        ""          },
    { OP_EXEC_MODE_SET,                     "",         "e"         },
    { OP_AWAIT,                             "",         ""          },
    { OP_MOTION_GET,                        "iiii",     ""          },
    { OP_MOTION_SET,                        "",         "iiii"      },
    { OP_MOTION_TIMESTAMP_GET,              "iiiiu",    ""          },
    { OP_SPEED_CONTROL_MODE_GET,            "e",        ""          },
    { OP_SPEED_CONTROL_MODE_SET,            "",         "e"         },
    { OP_ECHO_GET,                          "e",        ""          },
    { OP_ECHO_SET,                          "",         "e"         },
    { OP_FEEDBACK_GET,                      "e",        ""          },
    { OP_FEEDBACK_SET,                      "",         "e"         },
    { OP_HALT,                              "",         "e"         },
    { OP_JOYSTICK_GET,                      "e",        ""          },
    { OP_LIMIT_GET,                         "e",        ""          },
    { OP_LIMIT_SET,                         "",         "e"         },
    { OP_MONITOR_DEFAULT,                   "",         ""          },
    { OP_MONITOR_PAN,                       "",         "ii"        },
    { OP_MONITOR_ALL,                       "",         "iiii"      },
    { OP_MONITOR_ENABLE,                    "",         "e"         },
    { OP_MONITOR_GET,                       "e",        ""          },
    { OP_MONITOR_STATUS_GET,                "u",        ""          },
    { OP_ENVIRON_GET,                       "diii",     ""          },
    { OP_RESET,                             "",         "e"         },
    { OP_RESET_TYPE,                        "e",        ""          },
    { OP_UNIT_ID_GET,                       "u",        ""          },
    { OP_UNIT_ID_SET,                       "",         "u"         },
    { OP_SW_VERSION_GET,                    "s",        ""          },
    { OP_SW_VERSION_SHORT_GET,              "s",        ""          },
    { OP_COMPAT_GET,                        "e",        ""          },
    { OP_COMPAT_SET,                        "",         "e"         },
    { OP_DEFAULT_FACTORY,                   "",         ""          },
    { OP_DEFAULT_RESTORE,                   "",         ""          },
    { OP_DEFAULT_SAVE,                      "",         ""          },
    { OP_NET_MAC_GET,                       "s",        ""          },
    { OP_NET_MAC_SET,                       "",         "s"         },
    { OP_NET_FIREWALL_PUSH,                 "",         "s"         },
    { OP_NET_FIREWALL_POP,                  "s",        ""          },
    { OP_NET_FIREWALL_FLUSH,                "",         ""          },
    { OP_NET_FIREWALL_COUNT,                "i",        ""          },
    { OP_NET_FIREWALL_INDEX_GET,            "s",        "i"         },
    { OP_NET_FIREWALL_INDEX_SET,            "",         "is"        },
    { OP_NET_FIREWALL_APPLY,                "",         ""          },
    { OP_NET_GATEWAY_GET,                   "s",        ""          },
    { OP_NET_GATEWAY_SET,                   "",         "s"         },
    { OP_NET_IP_GET,                        "s",        ""          },
    { OP_NET_IP_SET,                        "",         "s"         },
    { OP_NET_MODE_GET,                      "e",        ""          },
    { OP_NET_MODE_SET,                      "",         "e"         },
    { OP_NET_HOSTNAME_GET,                  "s",        ""          },
    { OP_NET_HOSTNAME_SET,                  "",         "s"         },
    { OP_NET_NETMASK_GET,                   "s",        ""          },
    { OP_NET_NETMASK_SET,                   "",         "s"         },
    { OP_PELCO_PARSE_GET,                   "e",        ""          },
    { OP_PELCO_PARSE_SET,                   "",         "e"         },
    { OP_PELCO_ADDRESS_GET,                 "u",        ""          },
    { OP_PELCO_ADDRESS_SET,                 "",         "u"         },
    { OP_PAN_STEP_GET,                      "e",        ""          },
    { OP_PAN_STEP_SET,                      "",         "e"         },
    { OP_TILT_STEP_GET,                     "e",        ""          },
    { OP_TILT_STEP_SET,                     "",         "e"         },
    { OP_SERIAL_GET,                        "u",        ""          },
    { OP_MODEL_GET,                         "s",        ""          },
    { OP_PRESET_GO,                         "",         "u"         },
    { OP_PRESET_SET,                        "",         "u"         },
    { OP_PRESET_CLEAR,                      "",         "u"         },
    { OP_OPIO_OUT,                          "",         "ei"        },
    { OP_RESERVED_AAH,                      "",         ""          },
    { OP_RESERVED_AAI,                      "",         ""          },
    { OP_RESERVED_AAJ,                      "",         ""          },
    { OP_RESERVED_AAK,                      "",         ""          },
    { OP_RESERVED_AAL,                      "",         ""          },
    { OP_RESERVED_AAM,                      "",         ""          },
    { OP_RESERVED_AAN,                      "",         ""          },
    { OP_RESERVED_AAO,                      "",         ""          },
    { OP_RESERVED_AAP,                      "",         ""          },
    { OP_RESERVED_AAQ,                      "",         ""          },
    { OP_RESERVED_AAR,                      "",         ""          },
    { OP_RESERVED_AAS,                      "",         ""          },
    { OP_RESERVED_AAT,                      "",         ""          },
    { OP_RESERVED_AAU,                      "",         ""          },
    { OP_RESERVED_AAV,                      "",         ""          },
    { OP_RESERVED_AAW,                      "",         ""          },
    { OP_RESERVED_AAX,                      "",         ""          },
    { OP_RESERVED_AAY,                      "",         ""          },
    { OP_RESERVED_AAZ,                      "",         ""          },
    { OP_RESERVED_ABA,                      "",         ""          },
    { OP_RESERVED_ABB,                      "",         ""          },
    { OP_RESERVED_ABC,                      "",         ""          },
    { OP_RESERVED_ABD,                      "",         ""          },
    { OP_RESERVED_ABE,                      "",         ""          },
    { OP_RESERVED_ABF,                      "",         ""          },
    { OP_RESERVED_ABG,                      "",         ""          },
    { OP_RESERVED_ABH,                      "",         ""          },
    { OP_RESERVED_ABI,                      "",         ""          },
    { OP_RESERVED_ABJ,                      "",         ""          },
    { OP_RESERVED_ABK,                      "",         ""          },
    { OP_RESERVED_ABL,                      "",         ""          },
    { OP_RESERVED_ABM,                      "",         ""          },
    { OP_RESERVED_ABN,                      "",         ""          },
    { OP_RESERVED_ABO,                      "",         ""          },
    { OP_RESERVED_ABP,                      "",         ""          },
    { OP_RESERVED_ABQ,                      "",         ""          },
    { OP_RESERVED_ABR,                      "",         ""          },
    { OP_RESERVED_ABS,                      "",         ""          },
    { OP_RESERVED_ABT,                      "",         ""          },
    { OP_HOST_SETTINGS_SET,                 "",         "uue"       },
    { OP_CHA_SETTINGS_SET,                  "",         "uuee"      },
    { OP_CHB_SETTINGS_SET,                  "",         "uuee"      },
    { OP_CH_RX,                             "b",        "ei"        },
    { OP_CH_TX,                             "i",        "eb"        },
    { OP_RESERVED_ABU,                      "",         ""          },
    { OP_NET_REDIRECT_GET,                  "u",        "eu"        },
    { OP_NET_REDIRECT_SET,                  "",         "euu"       },
    { OP_RESET_CLASSIC_DWELL_GET,           "i",        ""          },
    { OP_RESET_CLASSIC_DWELL_SET,           "",         "i"         },
    { OP_RESET_PAN_SPEED_GET,               "i",        ""          },
    { OP_RESET_PAN_SPEED_SET,               "",         "i"         },
    { OP_RESET_TILT_SPEED_GET,              "i",        ""          },
    { OP_RESET_TILT_SPEED_SET,              "",         "i"         },
    { OP_RESET_CLASSIC_SEEKING_GET,         "e",        ""          },
    { OP_RESET_CLASSIC_SEEKING_SET,         "",         "e"         },
    { OP_RESERVED_ABV,                      "",         ""          },
    { OP_RESERVED_ABW,                      "",         ""          },
    { OP_ISM_CMD_TYPE_GET,                  "e",        ""          }
};

struct cpi_strop {
    const char *str;  /**< opcode name as a string */
    cpi_opcode op;    /**< opcode */
};
static struct cpi_strop cpi_stropname[] = {
    { "OP_AWAIT", OP_AWAIT },
    { "OP_CHA_SETTINGS_SET", OP_CHA_SETTINGS_SET },
    { "OP_CHB_SETTINGS_SET", OP_CHB_SETTINGS_SET },
    { "OP_CH_RX", OP_CH_RX },
    { "OP_CH_TX", OP_CH_TX },
    { "OP_COMPAT_GET", OP_COMPAT_GET },
    { "OP_COMPAT_SET", OP_COMPAT_SET },
    { "OP_CONTROL_PAN_CORRECTIONS_GET", OP_CONTROL_PAN_CORRECTIONS_GET },
    { "OP_CONTROL_TILT_CORRECTIONS_GET", OP_CONTROL_TILT_CORRECTIONS_GET },
    { "OP_CONTROL_TYPE_GET", OP_CONTROL_TYPE_GET },
    { "OP_CONTROL_TYPE_SET", OP_CONTROL_TYPE_SET },
    { "OP_DEFAULT_FACTORY", OP_DEFAULT_FACTORY },
    { "OP_DEFAULT_RESTORE", OP_DEFAULT_RESTORE },
    { "OP_DEFAULT_SAVE", OP_DEFAULT_SAVE },
    { "OP_ECHO_GET", OP_ECHO_GET },
    { "OP_ECHO_SET", OP_ECHO_SET },
    { "OP_ENVIRON_GET", OP_ENVIRON_GET },
    { "OP_EXEC_MODE_GET", OP_EXEC_MODE_GET },
    { "OP_EXEC_MODE_SET", OP_EXEC_MODE_SET },
    { "OP_FEEDBACK_GET", OP_FEEDBACK_GET },
    { "OP_FEEDBACK_SET", OP_FEEDBACK_SET },
    { "OP_GEO_ALT_GET", OP_GEO_ALT_GET },
    { "OP_GEO_ALT_SET", OP_GEO_ALT_SET },
    { "OP_GEO_CAL", OP_GEO_CAL },
    { "OP_GEO_CAL_QUALITY_GET", OP_GEO_CAL_QUALITY_GET },
    { "OP_GEO_CAM_PITCH_GET", OP_GEO_CAM_PITCH_GET },
    { "OP_GEO_CAM_PITCH_SET", OP_GEO_CAM_PITCH_SET },
    { "OP_GEO_DEFAULT_FACTORY", OP_GEO_DEFAULT_FACTORY },
    { "OP_GEO_DEFAULT_RESTORE", OP_GEO_DEFAULT_RESTORE },
    { "OP_GEO_DEFAULT_SAVE", OP_GEO_DEFAULT_SAVE },
    { "OP_GEO_DIST_LANDMARK", OP_GEO_DIST_LANDMARK },
    { "OP_GEO_DIST_LLA", OP_GEO_DIST_LLA },
    { "OP_GEO_LAND_ADD", OP_GEO_LAND_ADD },
    { "OP_GEO_LAND_CLEAR", OP_GEO_LAND_CLEAR },
    { "OP_GEO_LAND_DEL_IDX", OP_GEO_LAND_DEL_IDX },
    { "OP_GEO_LAND_DEL_LAST", OP_GEO_LAND_DEL_LAST },
    { "OP_GEO_LAND_IDX_GET", OP_GEO_LAND_IDX_GET },
    { "OP_GEO_LAND_NUM_GET", OP_GEO_LAND_NUM_GET },
    { "OP_GEO_LAND_PRINT_GET", OP_GEO_LAND_PRINT_GET },
    { "OP_GEO_LAT_GET", OP_GEO_LAT_GET },
    { "OP_GEO_LAT_SET", OP_GEO_LAT_SET },
    { "OP_GEO_LLA_GET", OP_GEO_LLA_GET },
    { "OP_GEO_LLA_SET", OP_GEO_LLA_SET },
    { "OP_GEO_LON_GET", OP_GEO_LON_GET },
    { "OP_GEO_LON_SET", OP_GEO_LON_SET },
    { "OP_GEO_POINT_LANDMARK", OP_GEO_POINT_LANDMARK },
    { "OP_GEO_POINT_LAST", OP_GEO_POINT_LAST },
    { "OP_GEO_POINT_LLA", OP_GEO_POINT_LLA },
    { "OP_GEO_POINT_TYPE_GET", OP_GEO_POINT_TYPE_GET },
    { "OP_GEO_POINT_TYPE_SET", OP_GEO_POINT_TYPE_SET },
    { "OP_GEO_PTU_PITCH_GET", OP_GEO_PTU_PITCH_GET },
    { "OP_GEO_PTU_PITCH_SET", OP_GEO_PTU_PITCH_SET },
    { "OP_GEO_PTU_ROLL_GET", OP_GEO_PTU_ROLL_GET },
    { "OP_GEO_PTU_ROLL_SET", OP_GEO_PTU_ROLL_SET },
    { "OP_GEO_PTU_RPY_GET", OP_GEO_PTU_RPY_GET },
    { "OP_GEO_PTU_RPY_SET", OP_GEO_PTU_RPY_SET },
    { "OP_GEO_PTU_YAW_GET", OP_GEO_PTU_YAW_GET },
    { "OP_GEO_PTU_YAW_SET", OP_GEO_PTU_YAW_SET },
    { "OP_GEO_STATUS_GET", OP_GEO_STATUS_GET },
    { "OP_HALT", OP_HALT },
    { "OP_HOST_SETTINGS_SET", OP_HOST_SETTINGS_SET },
    { "OP_INVALID", OP_INVALID },
    { "OP_ISM_CAM_PITCH_OFFSET_GET", OP_ISM_CAM_PITCH_OFFSET_GET },
    { "OP_ISM_CAM_PITCH_OFFSET_SET", OP_ISM_CAM_PITCH_OFFSET_SET },
    { "OP_ISM_CMD_MODE_GET", OP_ISM_CMD_MODE_GET },
    { "OP_ISM_CMD_MODE_SET", OP_ISM_CMD_MODE_SET },
    { "OP_ISM_CMD_TYPE_GET", OP_ISM_CMD_TYPE_GET },
    { "OP_ISM_DEFAULT_FACTORY", OP_ISM_DEFAULT_FACTORY },
    { "OP_ISM_DEFAULT_RESTORE", OP_ISM_DEFAULT_RESTORE },
    { "OP_ISM_DEFAULT_SAVE", OP_ISM_DEFAULT_SAVE },
    { "OP_ISM_GYRO_CAL", OP_ISM_GYRO_CAL },
    { "OP_ISM_GYRO_FIRMWARE_STATUS_GET", OP_ISM_GYRO_FIRMWARE_STATUS_GET },
    { "OP_ISM_GYRO_UPGRADE", OP_ISM_GYRO_UPGRADE },
    { "OP_ISM_GYRO_UTC_GET", OP_ISM_GYRO_UTC_GET },
    { "OP_ISM_GYRO_UTC_SET", OP_ISM_GYRO_UTC_SET },
    { "OP_ISM_HEAD_PAN_GAIN_GET", OP_ISM_HEAD_PAN_GAIN_GET },
    { "OP_ISM_HEAD_PAN_GAIN_SET", OP_ISM_HEAD_PAN_GAIN_SET },
    { "OP_ISM_HEAD_PAN_POS_CUR_GET", OP_ISM_HEAD_PAN_POS_CUR_GET },
    { "OP_ISM_HEAD_PAN_POS_DES_GET", OP_ISM_HEAD_PAN_POS_DES_GET },
    { "OP_ISM_HEAD_PAN_POS_DES_SET", OP_ISM_HEAD_PAN_POS_DES_SET },
    { "OP_ISM_HEAD_PAN_POS_REL_SET", OP_ISM_HEAD_PAN_POS_REL_SET },
    { "OP_ISM_HEAD_PAN_SPD_CUR_GET", OP_ISM_HEAD_PAN_SPD_CUR_GET },
    { "OP_ISM_HEAD_PAN_SPD_DES_GET", OP_ISM_HEAD_PAN_SPD_DES_GET },
    { "OP_ISM_HEAD_PAN_SPD_DES_SET", OP_ISM_HEAD_PAN_SPD_DES_SET },
    { "OP_ISM_HEAD_PAN_SPD_REL_SET", OP_ISM_HEAD_PAN_SPD_REL_SET },
    { "OP_ISM_HEAD_TILT_GAIN_GET", OP_ISM_HEAD_TILT_GAIN_GET },
    { "OP_ISM_HEAD_TILT_GAIN_SET", OP_ISM_HEAD_TILT_GAIN_SET },
    { "OP_ISM_HEAD_TILT_POS_CUR_GET", OP_ISM_HEAD_TILT_POS_CUR_GET },
    { "OP_ISM_HEAD_TILT_POS_DES_GET", OP_ISM_HEAD_TILT_POS_DES_GET },
    { "OP_ISM_HEAD_TILT_POS_DES_SET", OP_ISM_HEAD_TILT_POS_DES_SET },
    { "OP_ISM_HEAD_TILT_POS_REL_SET", OP_ISM_HEAD_TILT_POS_REL_SET },
    { "OP_ISM_HEAD_TILT_SPD_CUR_GET", OP_ISM_HEAD_TILT_SPD_CUR_GET },
    { "OP_ISM_HEAD_TILT_SPD_DES_GET", OP_ISM_HEAD_TILT_SPD_DES_GET },
    { "OP_ISM_HEAD_TILT_SPD_DES_SET", OP_ISM_HEAD_TILT_SPD_DES_SET },
    { "OP_ISM_HEAD_TILT_SPD_REL_SET", OP_ISM_HEAD_TILT_SPD_REL_SET },
    { "OP_ISM_LOS_MODE_GET", OP_ISM_LOS_MODE_GET },
    { "OP_ISM_LOS_MODE_SET", OP_ISM_LOS_MODE_SET },
    { "OP_ISM_PAN_IW_GET", OP_ISM_PAN_IW_GET },
    { "OP_ISM_PAN_IW_SET", OP_ISM_PAN_IW_SET },
    { "OP_ISM_PAN_KA_GET", OP_ISM_PAN_KA_GET },
    { "OP_ISM_PAN_KA_SET", OP_ISM_PAN_KA_SET },
    { "OP_ISM_PAN_KD_GET", OP_ISM_PAN_KD_GET },
    { "OP_ISM_PAN_KD_SET", OP_ISM_PAN_KD_SET },
    { "OP_ISM_PAN_KF_GET", OP_ISM_PAN_KF_GET },
    { "OP_ISM_PAN_KF_SET", OP_ISM_PAN_KF_SET },
    { "OP_ISM_PAN_KI_GET", OP_ISM_PAN_KI_GET },
    { "OP_ISM_PAN_KI_SET", OP_ISM_PAN_KI_SET },
    { "OP_ISM_PAN_KP_GET", OP_ISM_PAN_KP_GET },
    { "OP_ISM_PAN_KP_SET", OP_ISM_PAN_KP_SET },
    { "OP_ISM_PAN_KS_GET", OP_ISM_PAN_KS_GET },
    { "OP_ISM_PAN_KS_SET", OP_ISM_PAN_KS_SET },
    { "OP_ISM_PAN_KV_GET", OP_ISM_PAN_KV_GET },
    { "OP_ISM_PAN_KV_SET", OP_ISM_PAN_KV_SET },
    { "OP_ISM_PAN_PD_GET", OP_ISM_PAN_PD_GET },
    { "OP_ISM_PAN_PD_SET", OP_ISM_PAN_PD_SET },
    { "OP_ISM_PAN_VD_GET", OP_ISM_PAN_VD_GET },
    { "OP_ISM_PAN_VD_SET", OP_ISM_PAN_VD_SET },
    { "OP_ISM_RESET_UP_NORTH", OP_ISM_RESET_UP_NORTH },
    { "OP_ISM_STAB_DIS", OP_ISM_STAB_DIS },
    { "OP_ISM_STAB_EN", OP_ISM_STAB_EN },
    { "OP_ISM_STAB_HEAD_RESUME", OP_ISM_STAB_HEAD_RESUME },
    { "OP_ISM_STAB_PAN_POS_CUR_GET", OP_ISM_STAB_PAN_POS_CUR_GET },
    { "OP_ISM_STAB_PAN_POS_DES_GET", OP_ISM_STAB_PAN_POS_DES_GET },
    { "OP_ISM_STAB_PAN_POS_DES_SET", OP_ISM_STAB_PAN_POS_DES_SET },
    { "OP_ISM_STAB_PAN_POS_REL_SET", OP_ISM_STAB_PAN_POS_REL_SET },
    { "OP_ISM_STAB_PAN_SPD_CUR_GET", OP_ISM_STAB_PAN_SPD_CUR_GET },
    { "OP_ISM_STAB_PAN_SPD_DES_GET", OP_ISM_STAB_PAN_SPD_DES_GET },
    { "OP_ISM_STAB_PAN_SPD_DES_SET", OP_ISM_STAB_PAN_SPD_DES_SET },
    { "OP_ISM_STAB_PAN_SPD_REL_SET", OP_ISM_STAB_PAN_SPD_REL_SET },
    { "OP_ISM_STAB_TILT_POS_CUR_GET", OP_ISM_STAB_TILT_POS_CUR_GET },
    { "OP_ISM_STAB_TILT_POS_DES_GET", OP_ISM_STAB_TILT_POS_DES_GET },
    { "OP_ISM_STAB_TILT_POS_DES_SET", OP_ISM_STAB_TILT_POS_DES_SET },
    { "OP_ISM_STAB_TILT_POS_REL_SET", OP_ISM_STAB_TILT_POS_REL_SET },
    { "OP_ISM_STAB_TILT_SPD_CUR_GET", OP_ISM_STAB_TILT_SPD_CUR_GET },
    { "OP_ISM_STAB_TILT_SPD_DES_GET", OP_ISM_STAB_TILT_SPD_DES_GET },
    { "OP_ISM_STAB_TILT_SPD_DES_SET", OP_ISM_STAB_TILT_SPD_DES_SET },
    { "OP_ISM_STAB_TILT_SPD_REL_SET", OP_ISM_STAB_TILT_SPD_REL_SET },
    { "OP_ISM_STATUS_GET", OP_ISM_STATUS_GET },
    { "OP_ISM_TILT_IW_GET", OP_ISM_TILT_IW_GET },
    { "OP_ISM_TILT_IW_SET", OP_ISM_TILT_IW_SET },
    { "OP_ISM_TILT_KA_GET", OP_ISM_TILT_KA_GET },
    { "OP_ISM_TILT_KA_SET", OP_ISM_TILT_KA_SET },
    { "OP_ISM_TILT_KD_GET", OP_ISM_TILT_KD_GET },
    { "OP_ISM_TILT_KD_SET", OP_ISM_TILT_KD_SET },
    { "OP_ISM_TILT_KF_GET", OP_ISM_TILT_KF_GET },
    { "OP_ISM_TILT_KF_SET", OP_ISM_TILT_KF_SET },
    { "OP_ISM_TILT_KI_GET", OP_ISM_TILT_KI_GET },
    { "OP_ISM_TILT_KI_SET", OP_ISM_TILT_KI_SET },
    { "OP_ISM_TILT_KP_GET", OP_ISM_TILT_KP_GET },
    { "OP_ISM_TILT_KP_SET", OP_ISM_TILT_KP_SET },
    { "OP_ISM_TILT_KS_GET", OP_ISM_TILT_KS_GET },
    { "OP_ISM_TILT_KS_SET", OP_ISM_TILT_KS_SET },
    { "OP_ISM_TILT_KV_GET", OP_ISM_TILT_KV_GET },
    { "OP_ISM_TILT_KV_SET", OP_ISM_TILT_KV_SET },
    { "OP_ISM_TILT_PD_GET", OP_ISM_TILT_PD_GET },
    { "OP_ISM_TILT_PD_SET", OP_ISM_TILT_PD_SET },
    { "OP_ISM_TILT_VD_GET", OP_ISM_TILT_VD_GET },
    { "OP_ISM_TILT_VD_SET", OP_ISM_TILT_VD_SET },
    { "OP_ISM_X_BIAS_GET", OP_ISM_X_BIAS_GET },
    { "OP_ISM_X_BIAS_SET", OP_ISM_X_BIAS_SET },
    { "OP_ISM_Y_BIAS_GET", OP_ISM_Y_BIAS_GET },
    { "OP_ISM_Y_BIAS_SET", OP_ISM_Y_BIAS_SET },
    { "OP_ISM_Z_BIAS_GET", OP_ISM_Z_BIAS_GET },
    { "OP_ISM_Z_BIAS_SET", OP_ISM_Z_BIAS_SET },
    { "OP_JOYSTICK_GET", OP_JOYSTICK_GET },
    { "OP_LIMIT_GET", OP_LIMIT_GET },
    { "OP_LIMIT_SET", OP_LIMIT_SET },
    { "OP_MODEL_GET", OP_MODEL_GET },
    { "OP_MONITOR_ALL", OP_MONITOR_ALL },
    { "OP_MONITOR_DEFAULT", OP_MONITOR_DEFAULT },
    { "OP_MONITOR_ENABLE", OP_MONITOR_ENABLE },
    { "OP_MONITOR_GET", OP_MONITOR_GET },
    { "OP_MONITOR_PAN", OP_MONITOR_PAN },
    { "OP_MONITOR_STATUS_GET", OP_MONITOR_STATUS_GET },
    { "OP_MOTION_GET", OP_MOTION_GET },
    { "OP_MOTION_SET", OP_MOTION_SET },
    { "OP_MOTION_TIMESTAMP_GET", OP_MOTION_TIMESTAMP_GET },
    { "OP_NET_FIREWALL_APPLY", OP_NET_FIREWALL_APPLY },
    { "OP_NET_FIREWALL_COUNT", OP_NET_FIREWALL_COUNT },
    { "OP_NET_FIREWALL_FLUSH", OP_NET_FIREWALL_FLUSH },
    { "OP_NET_FIREWALL_INDEX_GET", OP_NET_FIREWALL_INDEX_GET },
    { "OP_NET_FIREWALL_INDEX_SET", OP_NET_FIREWALL_INDEX_SET },
    { "OP_NET_FIREWALL_POP", OP_NET_FIREWALL_POP },
    { "OP_NET_FIREWALL_PUSH", OP_NET_FIREWALL_PUSH },
    { "OP_NET_GATEWAY_GET", OP_NET_GATEWAY_GET },
    { "OP_NET_GATEWAY_SET", OP_NET_GATEWAY_SET },
    { "OP_NET_HOSTNAME_GET", OP_NET_HOSTNAME_GET },
    { "OP_NET_HOSTNAME_SET", OP_NET_HOSTNAME_SET },
    { "OP_NET_IP_GET", OP_NET_IP_GET },
    { "OP_NET_IP_SET", OP_NET_IP_SET },
    { "OP_NET_MAC_GET", OP_NET_MAC_GET },
    { "OP_NET_MAC_SET", OP_NET_MAC_SET },
    { "OP_NET_MODE_GET", OP_NET_MODE_GET },
    { "OP_NET_MODE_SET", OP_NET_MODE_SET },
    { "OP_NET_NETMASK_GET", OP_NET_NETMASK_GET },
    { "OP_NET_NETMASK_SET", OP_NET_NETMASK_SET },
    { "OP_NET_REDIRECT_GET", OP_NET_REDIRECT_GET },
    { "OP_NET_REDIRECT_SET", OP_NET_REDIRECT_SET },
    { "OP_NOOP", OP_NOOP },
    { "OP_OPIO_OUT", OP_OPIO_OUT },
    { "OP_PAN_ACCEL_GET", OP_PAN_ACCEL_GET },
    { "OP_PAN_ACCEL_SET", OP_PAN_ACCEL_SET },
    { "OP_PAN_BASE_SPEED_GET", OP_PAN_BASE_SPEED_GET },
    { "OP_PAN_BASE_SPEED_SET", OP_PAN_BASE_SPEED_SET },
    { "OP_PAN_CONTINUOUS_GET", OP_PAN_CONTINUOUS_GET },
    { "OP_PAN_CONTINUOUS_SET", OP_PAN_CONTINUOUS_SET },
    { "OP_PAN_CURRENT_POS_GET", OP_PAN_CURRENT_POS_GET },
    { "OP_PAN_CURRENT_SPEED_GET", OP_PAN_CURRENT_SPEED_GET },
    { "OP_PAN_DESIRED_POS_GET", OP_PAN_DESIRED_POS_GET },
    { "OP_PAN_DESIRED_POS_REL_SET", OP_PAN_DESIRED_POS_REL_SET },
    { "OP_PAN_DESIRED_POS_SET", OP_PAN_DESIRED_POS_SET },
    { "OP_PAN_DESIRED_SPEED_GET", OP_PAN_DESIRED_SPEED_GET },
    { "OP_PAN_DESIRED_SPEED_SET", OP_PAN_DESIRED_SPEED_SET },
    { "OP_PAN_HOLD_POWER_GET", OP_PAN_HOLD_POWER_GET },
    { "OP_PAN_HOLD_POWER_SET", OP_PAN_HOLD_POWER_SET },
    { "OP_PAN_LOWER_SPEED_LIMIT_GET", OP_PAN_LOWER_SPEED_LIMIT_GET },
    { "OP_PAN_LOWER_SPEED_LIMIT_SET", OP_PAN_LOWER_SPEED_LIMIT_SET },
    { "OP_PAN_MAX_POSITION", OP_PAN_MAX_POSITION },
    { "OP_PAN_MIN_POSITION", OP_PAN_MIN_POSITION },
    { "OP_PAN_MOVE_POWER_GET", OP_PAN_MOVE_POWER_GET },
    { "OP_PAN_MOVE_POWER_SET", OP_PAN_MOVE_POWER_SET },
    { "OP_PAN_REL_SPEED_SET", OP_PAN_REL_SPEED_SET },
    { "OP_PAN_RESOLUTION", OP_PAN_RESOLUTION },
    { "OP_PAN_STEP_GET", OP_PAN_STEP_GET },
    { "OP_PAN_STEP_SET", OP_PAN_STEP_SET },
    { "OP_PAN_UPPER_SPEED_LIMIT_GET", OP_PAN_UPPER_SPEED_LIMIT_GET },
    { "OP_PAN_UPPER_SPEED_LIMIT_SET", OP_PAN_UPPER_SPEED_LIMIT_SET },
    { "OP_PAN_USER_MAX_POS_GET", OP_PAN_USER_MAX_POS_GET },
    { "OP_PAN_USER_MAX_POS_SET", OP_PAN_USER_MAX_POS_SET },
    { "OP_PAN_USER_MIN_POS_GET", OP_PAN_USER_MIN_POS_GET },
    { "OP_PAN_USER_MIN_POS_SET", OP_PAN_USER_MIN_POS_SET },
    { "OP_PELCO_ADDRESS_GET", OP_PELCO_ADDRESS_GET },
    { "OP_PELCO_ADDRESS_SET", OP_PELCO_ADDRESS_SET },
    { "OP_PELCO_PARSE_GET", OP_PELCO_PARSE_GET },
    { "OP_PELCO_PARSE_SET", OP_PELCO_PARSE_SET },
    { "OP_PRESET_CLEAR", OP_PRESET_CLEAR },
    { "OP_PRESET_GO", OP_PRESET_GO },
    { "OP_PRESET_SET", OP_PRESET_SET },
    { "OP_RESET", OP_RESET },
    { "OP_RESET_CLASSIC_DWELL_GET", OP_RESET_CLASSIC_DWELL_GET },
    { "OP_RESET_CLASSIC_DWELL_SET", OP_RESET_CLASSIC_DWELL_SET },
    { "OP_RESET_CLASSIC_SEEKING_GET", OP_RESET_CLASSIC_SEEKING_GET },
    { "OP_RESET_CLASSIC_SEEKING_SET", OP_RESET_CLASSIC_SEEKING_SET },
    { "OP_RESET_PAN_SPEED_GET", OP_RESET_PAN_SPEED_GET },
    { "OP_RESET_PAN_SPEED_SET", OP_RESET_PAN_SPEED_SET },
    { "OP_RESET_TILT_SPEED_GET", OP_RESET_TILT_SPEED_GET },
    { "OP_RESET_TILT_SPEED_SET", OP_RESET_TILT_SPEED_SET },
    { "OP_RESET_TYPE", OP_RESET_TYPE },
    { "OP_SERIAL_GET", OP_SERIAL_GET },
    { "OP_SPEED_CONTROL_MODE_GET", OP_SPEED_CONTROL_MODE_GET },
    { "OP_SPEED_CONTROL_MODE_SET", OP_SPEED_CONTROL_MODE_SET },
    { "OP_SW_VERSION_GET", OP_SW_VERSION_GET },
    { "OP_SW_VERSION_SHORT_GET", OP_SW_VERSION_SHORT_GET },
    { "OP_TILT_ACCEL_GET", OP_TILT_ACCEL_GET },
    { "OP_TILT_ACCEL_SET", OP_TILT_ACCEL_SET },
    { "OP_TILT_BASE_SPEED_GET", OP_TILT_BASE_SPEED_GET },
    { "OP_TILT_BASE_SPEED_SET", OP_TILT_BASE_SPEED_SET },
    { "OP_TILT_CONTINUOUS_GET", OP_TILT_CONTINUOUS_GET },
    { "OP_TILT_CONTINUOUS_SET", OP_TILT_CONTINUOUS_SET },
    { "OP_TILT_CURRENT_POS_GET", OP_TILT_CURRENT_POS_GET },
    { "OP_TILT_CURRENT_SPEED_GET", OP_TILT_CURRENT_SPEED_GET },
    { "OP_TILT_DESIRED_POS_GET", OP_TILT_DESIRED_POS_GET },
    { "OP_TILT_DESIRED_POS_REL_SET", OP_TILT_DESIRED_POS_REL_SET },
    { "OP_TILT_DESIRED_POS_SET", OP_TILT_DESIRED_POS_SET },
    { "OP_TILT_DESIRED_SPEED_GET", OP_TILT_DESIRED_SPEED_GET },
    { "OP_TILT_DESIRED_SPEED_SET", OP_TILT_DESIRED_SPEED_SET },
    { "OP_TILT_HOLD_POWER_GET", OP_TILT_HOLD_POWER_GET },
    { "OP_TILT_HOLD_POWER_SET", OP_TILT_HOLD_POWER_SET },
    { "OP_TILT_LOWER_SPEED_LIMIT_GET", OP_TILT_LOWER_SPEED_LIMIT_GET },
    { "OP_TILT_LOWER_SPEED_LIMIT_SET", OP_TILT_LOWER_SPEED_LIMIT_SET },
    { "OP_TILT_MAX_POSITION", OP_TILT_MAX_POSITION },
    { "OP_TILT_MIN_POSITION", OP_TILT_MIN_POSITION },
    { "OP_TILT_MOVE_POWER_GET", OP_TILT_MOVE_POWER_GET },
    { "OP_TILT_MOVE_POWER_SET", OP_TILT_MOVE_POWER_SET },
    { "OP_TILT_REL_SPEED_SET", OP_TILT_REL_SPEED_SET },
    { "OP_TILT_RESOLUTION", OP_TILT_RESOLUTION },
    { "OP_TILT_STEP_GET", OP_TILT_STEP_GET },
    { "OP_TILT_STEP_SET", OP_TILT_STEP_SET },
    { "OP_TILT_UPPER_SPEED_LIMIT_GET", OP_TILT_UPPER_SPEED_LIMIT_GET },
    { "OP_TILT_UPPER_SPEED_LIMIT_SET", OP_TILT_UPPER_SPEED_LIMIT_SET },
    { "OP_TILT_USER_MAX_POS_GET", OP_TILT_USER_MAX_POS_GET },
    { "OP_TILT_USER_MAX_POS_SET", OP_TILT_USER_MAX_POS_SET },
    { "OP_TILT_USER_MIN_POS_GET", OP_TILT_USER_MIN_POS_GET },
    { "OP_TILT_USER_MIN_POS_SET", OP_TILT_USER_MIN_POS_SET },
    { "OP_TIMESTAMP_COUNT_GET", OP_TIMESTAMP_COUNT_GET },
    { "OP_TIMESTAMP_FREQUENCY", OP_TIMESTAMP_FREQUENCY },
    { "OP_UNIT_ID_GET", OP_UNIT_ID_GET },
    { "OP_UNIT_ID_SET", OP_UNIT_ID_SET }
};

/* case-sentive binary search comparitor for struct stropname */
static int cpi_strop_cmp(const void *va, const void *vb){
    struct cpi_strop *a = (struct cpi_strop *)va;
    struct cpi_strop *b = (struct cpi_strop *)vb;

    return strcmp(a->str, b->str);
}


/** Lookup an opcode by its name.
 *
 * \param opname   Opcode name
 *
 * \returns an opcode or OP_INVALID on error
 */
cpi_opcode cpi_opname_search(const char *opname){
    struct cpi_strop key, *hit;

    key.str = opname;
    if((hit = bsearch(&key, cpi_stropname, NEMB(cpi_stropname),
                    sizeof(struct cpi_strop), cpi_strop_cmp))){
        return hit->op;
    } else {
        return OP_INVALID;
    }
}

#ifdef CPI_CONFIG_USE_OP_LKUP
static int cpi_opent_cmp(const void *va, const void *vb){
    struct cpi_opent *a = (struct cpi_opent *)va;
    struct cpi_opent *b = (struct cpi_opent *)vb;

    return (a->op - b->op);
}

/* search cpi_opent for the matching opcode and return it or NULL on error */
struct cpi_opent *cpi_op_lkup(cpi_opcode op){
    struct cpi_opent key, *hit;

    key.op = op;
    if((hit = bsearch(&key, cpi_optable, NEMB(cpi_optable),
                    sizeof(struct cpi_opent), cpi_opent_cmp))){
        return hit;
    } else {
        return OP_INVALID;
    }
}
#endif

